num_workers: 0
pin_memory: False
non_blocking: True
prefetch: False
amp: False
device: cuda:0
client_optimizer: sgd
dataset: cifar10
dataset_path: ./data
frequency_save: 0
batch_size: 256  # Aumentado de 128 → 256
lr: 0.1  # Aumentado de 0.01 → 0.1
lr_scheduler: MultiStepLR  # Cambiado
steplr_milestones: [50, 75]  # Añadido
steplr_gamma: 0.1
model: preactresnet18
random_seed: 0
sgd_momentum: 0.9
wd: 0.0005
epochs: 100