attack: badnet
attack_label_trans: all2one
attack_target: 0
pratio: 0.1
patch_mask_path: ./resource/badnet/trigger_image.png
dataset: cifar10
dataset_path: ./data/cifar10
random_seed: 0
num_classes: 10
batch_size: 256
lr: 0.1
epochs: 100

# Model settings
model: preactresnet18
num_workers: 0
pin_memory: false
frequency_save: 10
amp: true  # Ahora funcionará con CUDA
prefetch: false
non_blocking: false

# Optimizer settings
client_optimizer: sgd
sgd_momentum: 0.9
wd: 0.0005

# Scheduler settings
lr_scheduler: MultiStepLR
steplr_milestones: [50, 75]
steplr_gamma: 0.1

# Device
device: cuda:0  # Ahora debería funcionar